In [ ]:
# 1.  Write a program that prints your name 100 times. 

for i in range(101):
    print("Name")

In [2]:
# Write a program to fill the screen horizontally and vertically with your name. 
#[Hint: add the option end=' ' into the print function to fill the screen horizontally.] 

for i in range(101):
    print("Name",end='')

NameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameName

In [3]:
# 3. Write a program that outputs 100 lines, numbered 1 to 100, each with your name on it. The output should look like the output below. 

for i in range(1,101):
    print(i, "Name")

1 Name
2 Name
3 Name
4 Name
5 Name
6 Name
7 Name
8 Name
9 Name
10 Name
11 Name
12 Name
13 Name
14 Name
15 Name
16 Name
17 Name
18 Name
19 Name
20 Name
21 Name
22 Name
23 Name
24 Name
25 Name
26 Name
27 Name
28 Name
29 Name
30 Name
31 Name
32 Name
33 Name
34 Name
35 Name
36 Name
37 Name
38 Name
39 Name
40 Name
41 Name
42 Name
43 Name
44 Name
45 Name
46 Name
47 Name
48 Name
49 Name
50 Name
51 Name
52 Name
53 Name
54 Name
55 Name
56 Name
57 Name
58 Name
59 Name
60 Name
61 Name
62 Name
63 Name
64 Name
65 Name
66 Name
67 Name
68 Name
69 Name
70 Name
71 Name
72 Name
73 Name
74 Name
75 Name
76 Name
77 Name
78 Name
79 Name
80 Name
81 Name
82 Name
83 Name
84 Name
85 Name
86 Name
87 Name
88 Name
89 Name
90 Name
91 Name
92 Name
93 Name
94 Name
95 Name
96 Name
97 Name
98 Name
99 Name
100 Name

4. Write a program that prints out a list of the integers from 1 to 20 and their squares. The output should look like this:

1 --- 1
2 --- 4
3 --- 9
...
20 --- 400

In [4]:
for i in range (1,201):
    print(i, "---", i*i)

1 --- 1
2 --- 4
3 --- 9
4 --- 16
5 --- 25
6 --- 36
7 --- 49
8 --- 64
9 --- 81
10 --- 100
11 --- 121
12 --- 144
13 --- 169
14 --- 196
15 --- 225
16 --- 256
17 --- 289
18 --- 324
19 --- 361
20 --- 400
21 --- 441
22 --- 484
23 --- 529
24 --- 576
25 --- 625
26 --- 676
27 --- 729
28 --- 784
29 --- 841
30 --- 900
31 --- 961
32 --- 1024
33 --- 1089
34 --- 1156
35 --- 1225
36 --- 1296
37 --- 1369
38 --- 1444
39 --- 1521
40 --- 1600
41 --- 1681
42 --- 1764
43 --- 1849
44 --- 1936
45 --- 2025
46 --- 2116
47 --- 2209
48 --- 2304
49 --- 2401
50 --- 2500
51 --- 2601
52 --- 2704
53 --- 2809
54 --- 2916
55 --- 3025
56 --- 3136
57 --- 3249
58 --- 3364
59 --- 3481
60 --- 3600
61 --- 3721
62 --- 3844
63 --- 3969
64 --- 4096
65 --- 4225
66 --- 4356
67 --- 4489
68 --- 4624
69 --- 4761
70 --- 4900
71 --- 5041
72 --- 5184
73 --- 5329
74 --- 5476
75 --- 5625
76 --- 5776
77 --- 5929
78 --- 6084
79 --- 6241
80 --- 6400
81 --- 6561
82 --- 6724
83 --- 6889
84 --- 7056
85 --- 7225
86 --- 7396
87 --- 7569
88 --- 7744
89 --- 7921
90 --- 8100
91 --- 8281
92 --- 8464
93 --- 8649
94 --- 8836
95 --- 9025
96 --- 9216
97 --- 9409
98 --- 9604
99 --- 9801
100 --- 10000
101 --- 10201
102 --- 10404
103 --- 10609
104 --- 10816
105 --- 11025
106 --- 11236
107 --- 11449
108 --- 11664
109 --- 11881
110 --- 12100
111 --- 12321
112 --- 12544
113 --- 12769
114 --- 12996
115 --- 13225
116 --- 13456
117 --- 13689
118 --- 13924
119 --- 14161
120 --- 14400
121 --- 14641
122 --- 14884
123 --- 15129
124 --- 15376
125 --- 15625
126 --- 15876
127 --- 16129
128 --- 16384
129 --- 16641
130 --- 16900
131 --- 17161
132 --- 17424
133 --- 17689
134 --- 17956
135 --- 18225
136 --- 18496
137 --- 18769
138 --- 19044
139 --- 19321
140 --- 19600
141 --- 19881
142 --- 20164
143 --- 20449
144 --- 20736
145 --- 21025
146 --- 21316
147 --- 21609
148 --- 21904
149 --- 22201
150 --- 22500
151 --- 22801
152 --- 23104
153 --- 23409
154 --- 23716
155 --- 24025
156 --- 24336
157 --- 24649
158 --- 24964
159 --- 25281
160 --- 25600
161 --- 25921
162 --- 26244
163 --- 26569
164 --- 26896
165 --- 27225
166 --- 27556
167 --- 27889
168 --- 28224
169 --- 28561
170 --- 28900
171 --- 29241
172 --- 29584
173 --- 29929
174 --- 30276
175 --- 30625
176 --- 30976
177 --- 31329
178 --- 31684
179 --- 32041
180 --- 32400
181 --- 32761
182 --- 33124
183 --- 33489
184 --- 33856
185 --- 34225
186 --- 34596
187 --- 34969
188 --- 35344
189 --- 35721
190 --- 36100
191 --- 36481
192 --- 36864
193 --- 37249
194 --- 37636
195 --- 38025
196 --- 38416
197 --- 38809
198 --- 39204
199 --- 39601
200 --- 40000

In [5]:
# 5 Write a program that uses a for loop to print the numbers 8, 11, 14, 17, 20, â€¦, 83, 86, 89. 

for i in range(8,90,3):
    print(i)

8
11
14
17
20
23
26
29
32
35
38
41
44
47
50
53
56
59
62
65
68
71
74
77
80
83
86
89

In [6]:
# 6  Write a program that uses a for loop to print the numbers 100, 98, 96, â€¦, 4, 2. 

for i in range(100,1,-2):
    print(i)

100
98
96
94
92
90
88
86
84
82
80
78
76
74
72
70
68
66
64
62
60
58
56
54
52
50
48
46
44
42
40
38
36
34
32
30
28
26
24
22
20
18
16
14
12
10
8
6
4
2

In [8]:
# 7. Write a program that uses exactly four for loops to print the sequence of letters below.

# AAAAAAAAAABBBBBBBCDCDCDCDEFFFFFFG

for i in range(10):
    print("A", end='')
for i in range(7):
    print("B",end='')
for i in range(4):
    print("C",end='')
    print("D",end='')
print("E",end='')
for i in range(6):
    print("F",end='')
print("G",end='')

AAAAAAAAAABBBBBBBCDCDCDCDEFFFFFFG

In [9]:
# 8 Write a program that asks the user for their name and how many times to print it. The program should print out the user's name the specified number of times. 

name = input("Enter your name:")
times = int(input("Enter how many times you want to print it: "))
for i in range(times+1):
    print(name)

Enter your name: name
Enter how many times you want to print it:  5

name
name
name
name
name
name

In [10]:
''' 9 The Fibonacci numbers are the sequence below, where the first two numbers are 1, and each number thereafter is the sum of the two preceding numbers. 
Write a program that asks the user how many Fibonacci numbers to print and then prints that many.1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, '''

n = int(input("Enter how many Fibonacci numbers you want to print: "))
a, b = 1, 1

for i in range(n):
    print(a, end=", ")
    # Calculate the next number in the sequence
    a, b = b, a + b

Enter how many Fibonacci numbers you want to print:  3

1, 1, 2,